raise ImportError(
    "The pandas.io.wb module is moved to a separate package "
    "(pandas-datareader). After installing the pandas-datareader package "
    "(https://github.com/pydata/pandas-datareader), you can change "
    "the import ``from pandas.io import data, wb`` to "
    "``from pandas_datareader import data, wb``.")
